# SPDX-FileCopyrightText: 2023 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name = "bme280"
description = "Driver for BME280 Humidity sensor"
version = "2.0.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/bme280"
tags = ["sensor", "humidity", "temperature", "pressure", "driver"]
project-files = ["gnat/bme280.gpr"]

[configuration]
output_dir = "gnat"
generate_ada = false
generate_c = false

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"

[[depends-on]]
hal = "~0.3.0"
gnat = ">=11 & <2000" # Uses Ada 2022 syntax
